#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="${HERE}/usr/bin:$LD_LIBRARY_PATH"
export QML_IMPORT_PATH="${HERE}/usr/bin"
export QT_PLUGIN_PATH="${HERE}/usr/bin"
exec "${HERE}/usr/bin/desktop_editor" "$@"
